# Generated by Django 4.2 on 2023-04-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0002_remove_menu_name_item_slug_menu_slug_menu_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='item',
            name='menu',
        ),
        migrations.AddField(
            model_name='item',
            name='is_menu',
            field=models.BooleanField(default=False, verbose_name='Menu or not'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
