# Generated by Django 4.2 on 2023-04-13 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0003_rename_name_item_title_remove_item_menu_item_is_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree_menu.item'),
        ),
    ]
